# Generated by Django 4.2.5 on 2023-09-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0003_remove_producto_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
