# Generated by Django 4.2.5 on 2023-09-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0004_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
